### ISSUE TITLE
First indent line has leading white pixels and lines always stay black

### ISSUE THREAD

**Issue by CaderHancock** [legalnonsense/org-visual-outline#1]
On dark themes in doom, the outermost indent line *  is significantly wider than the inner lines. It is also a different color. [doom-one theme](https://imgur.com/a/sI0jKhk) [doom-gruvbox-light](https://imgur.com/a/rYsekdM) gives some hints i guess.

How do I fix this? I'm up to date with origin/master.

**Comment by legalnonsense** [comment]
I suspect what happened is that you changed your theme after loading org-visual-indent.el. The package sets the faces for `org-visual-indent-pipe-face` and `org-visual-indent-blank-pipe-face` when it is loaded based on the default face. 

You can set these yourself however you like. The foreground and background of `org-indent-blank-pipe-face` should match your background color, and foreground and background of `org-indent-pipe-face` should match your foreground color (or whatever color you want the lines to be). Setting both to a height of .1 will give you the thin line seen in the example. 

Try evaluating this, substituting the colors you want. 
```
(face-spec-set 'org-visual-indent-pipe-face
 `((t (:foreground "desired line color"
		    :background "desired line color"
		    :height .1)))
(face-spec-set 'org-visual-indent-blank-pipe-face
 `((t (:foreground "your background color"
		    :background "your background color"
		    :height .1)))
```
Or do this, which will reset the faces based on your current default face:
```
(face-spec-set 'org-visual-indent-pipe-face
	       `((t (:foreground ,(face-foreground 'default)
				 :background ,(face-foreground 'default)
				 :height .1))))
(face-spec-set 'org-visual-indent-blank-pipe-face
	       `((t (:foreground ,(face-background 'default)
				 :background ,(face-background 'default)
				 :height .1))))
```

Let me know if that fixes it.

**Comment by CaderHancock** [comment]
That does allow me to change colors. Now I just need to dig through the theme to get the right ones. :)
